name: Update Commands In Bulk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger an update request
        run: "curl --request POST --url ${{ secrets.DENO_DEPLOY_URL }}redeploy -H 'Authorization: ${{ secrets.REDEPLOY_AUTHORIZATION }}'"
        
